# Generated by Django 3.0.4 on 2020-03-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200328_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
