# Generated by Django 3.0.4 on 2020-03-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
